name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npm test

      - name: Release script (standard-version)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./release.sh standard-version
